# Can be used for all nodes
/**:                      
  ros__parameters:
    max_angular_velocity: 0.75
    max_linear_velocity: 2.20
    frame_id: "world"

control_unit_node:
  ros__parameters:
    control_unit: "keyboard" # joy, esp8266, keyboard
    device_name: "/dev/ttyUSB0"

commander_node:
  ros__parameters:
    vehicle_dimensions:
      - 0.58   # Vehicle Width
      - 1.00   # Vehicle Length
      - 0.05   # Vehicle Height
    lidar_rules:
      - 3.00    # Max Range
      - 0.05    # Min Range
      - 0.48    # Sensor Location (relative to vehicle)[X]
      - 0.0     # Sensor Location (relative to vehicle)[Y]
      - 0.18    # Sensor Location (relative to vehicle)[Z]

      # - 3.14   # Horizontal Max Angle
      # - -3.14  # Horizontal Min Angle
      # - 0.05   # Vertical Max Angle
      # - -0.05  # Vertical Min Angle
      # - 0.01   # Noise
      
screenshot_node:
  ros__parameters:
    input_source: "simulation" # camera, simulation

angle_filter_node:
  ros__parameters:
    max_angle: 60   # [deg]
    min_angle: 0  # [deg]

distance_filter_node:
  ros__parameters:
    max_distance: 4.0  # [m]  
    min_distance: 0.0  # [m]

create_model_node:
  ros__parameters:
    model_name: "marble_husky"
    world_name: "default"
    model_pose: [0.0, 0.0, 1.0] # [x, Y, Z]
    model_orientation: [0.0, 0.0, 0.0] # [Roll, Pitch, Yaw] rad
